import {GlobeThree} from "components/GlobeThree";
import {useWindowResize} from "hooks/useIsMobile";
import {ScrollingText} from "components/ScrollingText";

export const HomePage = () => {
  const [size] = useWindowResize();
  return <>
    <img className={'absolute -z-10 w-full h-full object-fill top-0'} alt={'background'}
         src={'/images/background-dark.jpg'}/>
    <h1 className={'text-8xl absolute font-bold animate-pulse'}>A Global Animation.</h1>
    <ScrollingText className={'absolute bottom-[16px] right-10 sm:bottom-[100px] sm:left-[400px] w-[260px] whitespace-pre-wrap  h-[240px] pl-4 border-2 border-solid rounded'}
    delay={4000}>
      {content}</ScrollingText>
    <GlobeThree className={'mt-[140px] sm:mt-10 cursor-grab roll-in'} size={size !== undefined && size.width <= 768 ? 320 : 600}/>

  </>
}

const content = `
(Text Generated by ChatGPT)

In the vast expanse of cosmic dance,
A jewel of wonder, our dear Earth, enchants.
From boundless depths to skies so high,
A canvas painted with nature's sigh.

Behold the Earth, a planet of grace,
A tapestry woven with life's embrace.
Her landscapes painted in vibrant hues,
From snowy peaks to oceanic blues.

Mountains rise, majestic and grand,
Ancient sentinels, guardians of the land.
Their peaks touch heavens with pride,
Where eagles soar and dreams abide.

Valleys stretch, lush and green,
A cradle for life, a tranquil scene.
Rivers meander, their gentle flow,
Nourishing plains where wildflowers grow.

Oceans vast, with depths untold,
A vast mosaic, teeming with life's gold.
Whales sing songs of ancient lore,
As dolphins dance along the shore.

Forests stand tall, a verdant maze,
A sanctuary for creatures, a haven's embrace.
Through whispering leaves, sunlight beams,
Embracing the Earth in nature's dreams.

In deserts vast, where heat prevails,
Resilient life weaves its arid tales.
From cacti standing against the sun,
To camels roaming, the sands they've won.

The Earth's embrace, a symphony of sound,
Birds in chorus, their melodies abound.
From chirping sparrows to nightingales,
Their songs reverberate through hills and dales.

Beneath the surface, secrets lie,
Caverns deep where wonders lie shy.
Glistening crystals, stalactites tall,
Unveiling Earth's treasures, one and all.

Yet, amidst her beauty, Earth is fragile,
Human hands shape her destiny, a vital mile.
We must tread gently, with mindful grace,
Preserving her wonders, for each future's trace.

Let us seek harmony, hand in hand,
With nature's rhythms, a united band.
For Earth is our home, a sacred place,
A gift to cherish, a legacy to embrace.

So let us protect her, with love profound,
For the Earth's beauty, in us, is found.
Through stewardship and mindful care,
A brighter future we can all share.

In the grand tapestry of the cosmic array,
The Earth shines bright, a beacon's display.
Let us be custodians, let our actions be wise,
For the Earth, our precious home, never dies.`